title: TAKWIMU
description: African Digital Service
author: africapractice, Code for Africa, iHub

url: https://takwimu.africa
enforce_ssl: takwimu.africa

tw_url: \#
fb_url: \#
gh_url: https://github.com/TakwimuAfrica
ig_url: \#

google_analytics: UA-115543098-1
